cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - vendor/
stages:
  - build
  - compile

variables:
    DC_PROJ: ${DC_NAME}_${CI_COMMIT_REF_NAME}
    DC_NAME: ipm
    DC_FILE: /usr/share/jwa-dockers/sites/${DC_NAME}_${CI_BUILD_REF_NAME}/docker-compose.yml

Build:
  stage: build
  only:
    - develop
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.j-wa.nl:5001
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME git checkout $CI_BUILD_REF_NAME
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME git pull origin $CI_BUILD_REF_NAME
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME composer install
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME php artisan migrate
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME php artisan config:cache

Compile:
  stage: compile
  only:
    - develop
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.j-wa.nl:5001
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME yarn install --production
