cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - vendor/
    - storage/
stages:
  - build
  - compile

variables:
    DC_PROJ: ${DC_NAME}_develop
    DC_NAME: ipm
    DC_FILE: /usr/share/jwa-dockers/sites/${DC_NAME}_develop/docker-compose.yml

Build:
  stage: build
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME git checkout $CI_BUILD_REF_NAME
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME git pull origin $CI_BUILD_REF_NAME
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME composer install
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME php artisan migrate
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME php artisan config:cache

Compile:
  stage: compile
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker-compose -p $DC_PROJ -f $DC_FILE exec -T $DC_NAME yarn install --production
